{% set name = "pygix" %}
{% set version = "2022.11.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d0f8c59f7036acc4e1433b21bb0c7e823ef1416bfa8a0d50c685bd6c82f36bb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy
  run:
    - python >={{ python_min }}
    - cython
    - fabio
    - numpy
    - pyfai
    - pyyaml
    # Note: the sphinx dependencies are listed in the project's
    # `requirements.txt` file. They are only optionally used in `setup.py`, and
    # not used in the main code base. So, commenting them out:
    # - sphinx
    # - sphinxcontrib-programoutput

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygix
    - pygix.grazing_geometry
    - pygix.grazing_units
    - pygix.io
    - pygix.lattice
    - pygix.plotting
    - pygix.process
    - pygix.tools
    - pygix.transform
    # The `pip check` command was commented out due to inconsistency of setuptools:
    #   pyfai 0.21.3 has requirement setuptools<60.0.0, but you have setuptools 65.5.1.
    # requires:
    #   - pip
    # commands:
    #   - pip check

about:
  home: https://github.com/tgdane/pygix
  summary: A python library for reduction of 2-dimensional grazing-incidence and fibre diffraction data
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/NSLS-II-SMI/pygix

extra:
  recipe-maintainers:
    - mrakitin
    - gfreychet
